models:
  - "google/gemini-flash-1.5-8b"
  - "google/gemini-2.0-flash-exp:free"
  - "google/gemini-exp-1121:free"

general:
  max_file_size: 16777216
  upload_folder: "uploads"

resume_schema:
  talent:
      first_name: string
      last_name: string
      email: string
      phone: string
      location: string
      summary: string
      current_title: string
      total_years_of_experience: number

      education:
        - degree: string
          institution: string
          start_date: string
          end_date: string
          grade: string
          description: string

      experience:
        - job_title: string
          company: string
          location: string
          start_date: string
          end_date: string
          description: string

      skills:
        - name: string
          proficiency: string